# Automatically generated file. DO NOT MODIFY
#
# This file is generated by device/realme/RM6785-common/setup-makefiles.sh

LOCAL_PATH := $(call my-dir)

ifneq ($(filter RMX2001L1 RMX2151L1,$(TARGET_DEVICE)),)

endif
